version: 3
services:
    node-server:
        build: ./backend/.
        container_name: node-server
        networks:
            - default
        ports:
            - "8080:8080"

networks:
    default:

volumes:
